### ISSUE TITLE
save not nesting roots correctly?

### ISSUE THREAD

**Issue by estebanlm** [estebanlm/voyage#1]
Damien reports this problem: 

I'm following the tutorial at
https://ci.inria.fr/pharo-contribution/job/EnterprisePharoBook/lastSuccessfulBuild/artifact/Voyage/Voyage.html.

In Sections "2.2. Embedding objects" and "2.3. Referencing other roots",
the tutorial says:

 1. add #isVoyageRoot to Rectangle and Point
 2. create a rectangle with "aRectangle := 42@1 corner: 10@20."
 3. send #save to the rectangle

In mongo, this results in having:

    show collections
    Associations
    Rectangle
    false
    system.indexes

    db.Rectangle.find()
    { "_id" : ObjectId("d710db9b4b673b0718000001"), "#instanceOf" : "Rectangle", "#version" : 856503121, "corner" : { "#collection" : "false", "#instanceOf" : "Point", "__id" : ObjectId("d710dc994b673b0718000003") }, "origin" : { "#collection" : "false", "#instanceOf" : "Point", "__id" : ObjectId("d710dc994b673b0718000002") } }

    db.false.find()
    { "_id" : ObjectId("d710dc994b673b0718000002"), "#version" : NumberLong("3790997929"), "#instanceOf" : "Point", "x" : 10, "y" : 1 }
    { "_id" : ObjectId("d710dc994b673b0718000003"), "#version" : 982787913, "#instanceOf" : "Point", "x" : 42, "y" : 20 }

So, no "Point" collection, and a "false" collection instead.

**Comment by DamienCassou** [comment]
I think the problem came from not having executed this

```smalltalk
VORepository current reset
````
after adding #isVoyageRoot to Point.

**Comment by estebanlm** [comment]
False alarm: 

I think the problem came from not having executed this

    VORepository current reset

after adding #isVoyageRoot to Point.
