### ISSUE TITLE
Optimize VOMongoRepositoryResolver>>newVersion

### ISSUE THREAD

**Issue by tinchodias** [estebanlm/voyage#16]
As discussed some tome ago in a [pharo-dev's thread](http://forum.world.st/Contributing-to-VoyageMongo-improving-insertion-updating-speed-td4838806.html), the implementation of `newVersion` is wrong, making VOMongoRepository's save: and update: operations slow.

This is the code:

	VOMongoRepositoryResolver>>
	newVersion 
		^UUIDGenerator new makeSeed

**Comment by tinchodias** [comment]
Now I'm confused. After some benchmarks (but in my old computer), the current implementation seems the faster!

	Gofer new
		smalltalkhubUser: #SvenVanCaekenberghe
		project: #Neo;
		package: 'Neo-UUID';
		load.
		
	[UUIDGenerator new makeSeed] bench. 
	"'394.763 per second'"
	[NeoUUIDGenerator next] bench.
	 "'101,508 per second'"
	[UUID new ] bench.
	 "'2,984 per second'"



No idea how to load the "libcrypto of OpenSSL" uuid generator mentioned by Holger...

(I'm on Linux, Pharo 50655)
Smalltalk vm version
"'CoInterpreter VMMaker.oscog-eem.1726 uuid: 6a968923-b541-4573-bc4f-64fb95e6462d Mar 15 2016
StackToRegisterMappingCogit VMMaker.oscog-eem.1726 uuid: 6a968923-b541-4573-bc4f-64fb95e6462d Mar 15 2016
https://github.com/pharo-project/pharo-vm.git Commit: 2b53ae43e6a030759fbfa6ce8737a7f55ba76dd1 Date: 2016-03-15 19:05:06 +0100 By: Esteban Lorenzano <estebanlm@gmail.com> Jenkins build #576
'"

**Comment by tinchodias** [comment]
Since there is no unique best UUID generator for all platforms/users, Voyage could allow customization API in VOMongoRepository.

The implementation can be a simple block:

	VOMongoRepositoryResolver>>
	newVersion 
		^ repository versionGeneratorBlock value

or use strategy design pattern (this looks *too* complex, but CompiledMethod execution may be faster than BlockClosure execution, in this critical operation):

	VOMongoRepositoryResolver>>
	newVersion 
		^ repository versionGenerationStrategy next


Opinion?

**Comment by tinchodias** [comment]
The block alternative adds no performance penalty in my computer:

	[ UUIDGenerator new makeSeed ] bench.
	 "'379.124 per second'" 
	[ [ UUIDGenerator new makeSeed ] value ] bench.
	 "'382.094 per second'"

**Comment by zecke** [comment]
UUIDGenerator new makeSeed vs. NeoUUIDGenerator next.

The one obviously picks a random seed (e.g. four bytes from /dev/urandom) and the other generates a full UUID. I think Esteban picked the UUIDGenerator because it provides a seed and not because he wants a UUID. (version != objectId)

Have you seen my original proposal:
http://smalltalkhub.com/#!/~hfreyther2/Junk/versions/Voyage-Mongo-Core-HolgerHansPeterFreyther.55
http://smalltalkhub.com/#!/~hfreyther2/Junk/versions/Voyage-Mongo-Tests-HolgerHansPeterFreyther.16

to make it pluggable/changable?

But yes, making it blocked base is fine as well.

**Comment by tinchodias** [comment]
Hi @zecke, I didn't know of those commits. You used the strategy-based approach which Esteban prefers, so I merged changes and created PR #24

**Comment by tinchodias** [comment]
We can close this since #24 is merged
