### ISSUE TITLE
Creation of Repository failed

### ISSUE THREAD

**Issue by mkemper** [estebanlm/voyage#3]
Hi Esteban,
first thanks for your work - maybe I found an issue, here is what I've done: 

loaded a fresh Pharo 4.0 image
loaded VoyageMongo via Configuration Browser (Install Stable Version)
opened up a Playground and did (via the green 'play' button):

|repository|

repository := VOMongoRepository 
	host:'hostOn.mongolab.com' 
	port: 43158
	database:'databasename' 
	username: 'username' 
	password: 'password'.

repository enableSingleton.

repository inspect.

This leads to an error which seems to be connected to 'gtInspectorMagritteIn:' which was updated in the package Magritte-GT on 03.06.2015. (no instance 'repository' is going to be created).

Please excuse my bad analysis on this, because I have only very limited skills.

Best regards

Marcus

**Comment by mkemper** [comment]
Solved by Sean P. deNigris via Updating Magritte.

**Comment by estebanlm** [comment]
yes, thanks... I was not around the weekend (also it was not a problem of voyage but magritte :P)

**Comment by mkemper** [comment]
Yeah, seems to be... :-) Btw: did you ever test VoyageMongo with something other than a local database? I can't connect to a test-database on mongolab.com... but local db works.

**Comment by estebanlm** [comment]
I *always* use other than localhost. I have all my databases inside a virtualised system (usually some kind of linux). Reason is that I work with tons of projects and I do not want to pollute my main system with endless different databases :) 
So, something like this: 

    VOMongoRepository host: 'narshaddaa' database: 'test'.

... should work if default port (27017) is open.

**Comment by mkemper** [comment]
☺ Sorry, didn't want to offend - it seems that I am not really familiar with projects of that kind. But good to know, so I will drill further in the network direction...

**Comment by estebanlm** [comment]
heh... don't worry. Most of my projects are just experiments or temporal stuff... even better reason to not have them in my main system :)
