### ISSUE TITLE
Inverted class hierarchy? VOMongoTest is superclass of VORepositoryTest

### ISSUE THREAD

**Issue by dalehenrich** [estebanlm/voyage#30]
I'm in the process of creating a VoyageGemStone implementation and VORepositoryTest has all of the interesting repository tests with no apparent dependencies upon VOMongoTest, so the hierarchy seems to be inverted where VORepositoryTest could be an abstract test that expects subclasses to implement #repository...

I've inverted the hierarchy in my fork and unless there's a reason for the inverted hierarchy I can provide a PR

**Comment by dalehenrich** [comment]
Presumably VORepositoryTest should be moved out of the Voyage-Mongo-Tests package, but then again there may be dependencies that I am not aware of ...

**Comment by dalehenrich** [comment]
VOMongoVisitorTest hierarchy is using a similar pattern where the concrete class is the superclass...

**Comment by tinchodias** [comment]
+1
I agree in that VOMongoTest should be subclass of VORepositoryTest.  I think only testSelectManyWithLimitAndOffset is mongo-specific, and maybe testSelectAllJustAfterRemove which is an expected failure only for mongo repositories.

**Comment by noha** [comment]
I don't think testSelectManyWithLimitAndOffset is mongo-specific. In any database we might use we will have the need to specify a query that has a filter criteria, a number of results and an offset parameter to skip entries in the result set. So only the naming is mongo-specific and maybe we should decide about the wording and then adjust the code.

**Comment by dalehenrich** [comment]
What are your thoughs on VOMongoVisitorTest? ... in this case I actually don't need to specialize these tests for VoyageGemStone as I'm using the same serialization scheme, but at one point I thought that I might need to customize the serialization scheme for GemStone ...
