### ISSUE TITLE
Infinite VOMongoConnectionError resignal loop

### ISSUE THREAD

**Issue by dalehenrich** [estebanlm/voyage#31]
If an Error occurs within [VOMongoSessionPool>>withDatabase:](https://github.com/estebanlm/voyage/blob/master/mc/Voyage-Mongo-Core.package/VOMongoSessionPool.class/instance/withDatabase..st) and [VOMongoRepositoryResolver>>execute:retries: is farther down the stack](https://github.com/estebanlm/voyage/blob/master/mc/Voyage-Mongo-Core.package/VOMongoRepositoryResolver.class/instance/execute.retries..st), you end up with an ifinite loop of VOMongoConnectionErrors

VOMongoSessionPool>>withDatabase: eats the original Error turns it into a VOMongoConnectionError which is caught by VOMongoRepositoryResolver>>execute:retries: and if you are out of retries resignals as VOMongoConnectionError and you are off to the races ...

With VOMongoRepositoryResolver>>execute:retries:  on the stack the connection error should not be resignalled ... not sure why the error should be turned into a VOMongoConnectionError ... 

I suppose with Mongo you are guaranteed that no non-connection-based errors are signalled? 

For GemStone, I have my own session pool so I can manage this differently, but any unexpected Errors signalled by the Mongo Smalltalk would result in a similar infinite loop --- not easy to debug

**Comment by tinchodias** [comment]
Hi Dale, this is already reported as #5

**Comment by dalehenrich** [comment]
oops :) thanks @tinchodias
