### ISSUE TITLE
Unit tests don't release or close open connections. 

### ISSUE THREAD

**Issue by Ironirc** [estebanlm/voyage#9]
With every run the number open connections grow.

**Comment by tinchodias** [comment]
Hi, I'm new to Voyage but I want to understand this issue. How can I reproduce/check the problem?

I inspected the session pool in `VOMongoTestResource current repository` and looked at the shared queue of Mongo instances, and they are always 10 (the default pool size). Are the Socket instances in such Mongo objects who need to be closed manually? 

I'm interested, this seems related to issue #8.

Thanks.

**Comment by Ironirc** [comment]
In windows cmd start mongod
	MongoDB starting : pid=10140 port=27017 dbpath=\data\db\ 64-bit host=PRT-TUBA
	targetMinOS: Windows 7/Windows Server 2008 R2
	db version v2.6.11
	...
	connections:0

Start with fresh Pharo 4.0 image
With configuration browser, find voyage and load stable version.

Set Pharo and cmd window side by side.

In pharo start "test runner" and find voyage
select all 5 test classes and run.

After the first run observe in cmd window
	connection accepted from 127.0.0.1:12194 #10 (10 connections now open)

run the tests again and observe cmd window
	connection accepted from 127.0.0.1:12276 #20 (20 connections now open)

**Comment by tinchodias** [comment]
Hi @Ironirc 
Issue reproduced in Pharo 4 w/stable version, but couldn't reproduce with development version.

**Comment by Ironirc** [comment]
I can confirm that the development version indeed resolves this issue.

**Comment by Ironirc** [comment]
I confirm that the development version doesn't have the problem.
